name: Staging deployment

on: 
  push:
    branches:
      - staging

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present


  deploy:
    name: Deploy Node.js app to Azure
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure
        with: 
          app-name: ActionTestNodeJS
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
