name: Staging deployment

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: npm install and build
        uses: actions/setup-node@v1
        run: |
          npm install
          npm run build --if-present
          
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ActionTestNodeJS
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
