name: Production deployment

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run build

  deploy:
    name: Deploy Node.js app to Azure
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ActionTestNodeJS
          publish-profile: ${{ secrets.azureWebAppPublishProfile_Production }}
